---
title: "Visualizing Titers"
author: "Stefan Avey"
date: "`r Sys.Date()`"
output: 
      rmarkdown::html_vignette:
        css: mystyles.css
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Format titer data
```{r readData}
library(titeR)

strains <- c("A_California_7_2009", "A_Perth_16_2009", "B_Brisbane_60_2008")
titer_list <- FormatTiters(Year1_Titers, strains,
                           subjectCol = "YaleID", otherCols = "AgeGroup")

```

## Bar plots

Bar plots can show the raw data, baseline and day 28 titer values for each subject.

```{r bars, fig.width = 9, fig.height = 6}

## Bar plot of B strain
Barplot(titer_list["A_Perth_16_2009"], subjectCol = "YaleID")

## Bar plot of all strains
Barplot(titer_list, subjectCol = "YaleID", groupVar = "AgeGroup")

```

## Bubble Charts

Bubble Charts show the relationship between baseline titer and fold change. In general, a negative slope is observed.

```{r bubbles, fig.width = 7, fig.height = 7}

## Bubble Charts for all strains
BubbleChart(titer_list)

## Bubble Chart for B strain
BubbleChart(titer_list["A_Perth_16_2009"])

## Add an exponential fit and color by age group
BubbleChart(titer_list["A_Perth_16_2009"], fit = "exp",
            subjectCol = "YaleID", colorBy = "AgeGroup",
            eqSize = 5)

```

<!-- Add footer to HTML -->
<div id="footer" class="footer">
<footer>
Built using <a href="http://rmarkdown.rstudio.com/index.html" target="_blank">R markdown</a> in `r R.version.string`.<br>
<a href="https://github.com/stefanavey/titeR" target="_blank">titeR</a> package version `r packageVersion("titeR")`.
</footer>
</div>
